repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        args:
          - --branch
          - main

      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: backend-ruff-check
        name: Backend Ruff lint
        entry: bash -c 'cd backend && uv run ruff check --fix .'
        language: system
        files: ^backend/.*\.py$

      - id: backend-ruff-format
        name: Backend Ruff format
        entry: bash -c 'cd backend && uv run ruff format .'
        language: system
        files: ^backend/.*\.py$

      - id: frontend-prettier
        name: Frontend Prettier
        entry: bash -c 'cd frontend && npm run format:write'
        language: system
        files: ^frontend/.*\.(js|jsx|ts|tsx|json|css|md|html)$
